#!perl

use lib 'web/lib';
use YAML qw/LoadFile DumpFile/;
use Grades;

$_REPL->load_plugin('DumpHistory');

my $leagueid = 'BMA0076';

my $l = League->new( id => $leagueid );
my $g = Grades->new( league => $l );
my $m = $l->members;
my %m = map { $_->{id} => $_ } @$m;

my $conversations = $g->conversations;
my @op = map { $g->opponents($_) } @$conversations;

use Swiss;
use Swiss::Model::DB;
use Swiss::Schema;

my $d = Swiss::Schema->connect( 'dbi:SQLite:web/db/982', '', '' );

my $o = $d->resultset('Opponents')->search({ tournament => $leagueid });
my $rol = $d->resultset('Roles')->search({ tournament => $leagueid });
my $f = $d->resultset('Floats')->search({ tournament => $leagueid });
my $r = $d->resultset('Ratings')->search({ tournament => $leagueid });
my $ro = $d->resultset('Round')->search({ tournament => $leagueid });
my $s = $d->resultset('Scores')->search({ tournament => $leagueid });

# $o->update_or_create({ tournament => 'GL00012', player => 'U9843022', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9843022', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9843022', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9843009', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9843009', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9843009', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9631006', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9631006', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9631006', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9723053', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9723053', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9723053', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9515010', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9515010', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9515010', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9633045', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9633045', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9633045', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9621111', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9621111', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9621111', float => 'Not', round => 1 });
# 
# 
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610015', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610015', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610015', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610015', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610015', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610015', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610015', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610015', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610015', float => 'Not', round => 3 });
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610042', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610042', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610042', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610042', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610042', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610042', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9610042', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9610042', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9610042', float => 'Not', round => 3 });
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'U9521030', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9521030', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9521030', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9521030', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9521030', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9521030', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9521030', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9521030', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9521030', float => 'Not', round => 3 });
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'U9711030', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9711030', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9711030', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9711030', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9711030', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9711030', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9711030', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9711030', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9711030', float => 'Not', round => 3 });
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'T9722022', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'T9722022', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'T9722022', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'T9722022', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'T9722022', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'T9722022', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'T9722022', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'T9722022', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'T9722022', float => 'Not', round => 3 });
# 
# $o->update_or_create({ tournament => 'GL00012', player => 'U9593023', opponent => 'Unpaired', round => 1 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9593023', role => 'Unpaired', round => 1 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9593023', float => 'Not', round => 1 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9593023', opponent => 'Unpaired', round => 2 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9593023', role => 'Unpaired', round => 2 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9593023', float => 'Not', round => 2 });
# $o->update_or_create({ tournament => 'GL00012', player => 'U9593023', opponent => 'Unpaired', round => 3 });
# $rol->update_or_create({ tournament => 'GL00012', player => 'U9593023', role => 'Unpaired', round => 3 });
# $f->update_or_create({ tournament => 'GL00012', player => 'U9593023', float => 'Not', round => 3 });

# $rol->update_or_create({ player => 'V9899132', round => 3, role => "White" });
# $rol->update_or_create({ player => 'N9561766', round => 3, role => "Black" });

# $rol->update_or_create({ player => 'V9731059', round => 4, role => 'Black' });
# $o->update_or_create({ player => 'V9731059', round => 4, opponent => 'V9741048' });
# $o->update_or_create({ player => 'V9741048', round => 4, opponent => 'V9731059' });

# $rol->update_or_create({ player => 'V9741047', round => 4, role => 'White' });
# $o->update_or_create({ player => 'V9741047', round => 4, opponent => 'V9741023' });
# $o->update_or_create({ player => 'V9741023', round => 4, opponent => 'V9741047' });

# my $o4 = LoadFile '/home/drbean/class/FLA0018/comp/4/opponent.yaml';
# my $r4 = LoadFile '/home/drbean/class/FLA0018/comp/4/role.yaml';
# $o->update_or_create({ round => 4, player => $_, opponent => $o4->{$_} }) for keys %m;
# $rol->update_or_create({ round => 4, player => $_, role => $r4->{$_} }) for keys %m;
# $f->update_or_create({ round => 4, player => $_, float => 'Not' }) for keys %m;

# $o->update_or_create({ tournament => 'FLA0018', player => 'U9593023', opponent => 'Unpaired', round => 1 });
# $o->update_or_create({ tournament => 'FLA0018', player => 'U9593023', opponent => 'Unpaired', round => 2 });
# $o->update_or_create({ tournament => 'FLA0018', player => 'U9593023', opponent => 'Unpaired', round => 3 });

# $o->update_or_create({ tournament => 'FLA0018', player => 'E9841001', opponent => 'Unpaired', round => 1 });
# $o->update_or_create({ tournament => 'FLA0018', player => 'E9841001', opponent => 'Unpaired', round => 2 });
# $o->update_or_create({ tournament => 'FLA0018', player => 'E9841001', opponent => 'Unpaired', round => 3 });

# $o->update_or_create({ tournament => 'FLA0018', player => 'V9741044', opponent => 'V9899132', round => 1 });
# $o->update_or_create({ tournament => 'FLA0018', player => 'V9899132', opponent => 'V9741044', round => 1 });

# $d->resultset( 'Round' )->update_or_create({ tournament => 'FLA0018', round => 3 });
